{
 "title": "Overview Profile",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Number of Applications",
   "type": "stat",
   "description": "Total number of applications in our database (each id is a individual loan application)",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT COUNT(*) FROM bankloandb.bankloan LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Funded Amount",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select sum(loan_amount) as total_funded_ammount from bankloan"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "description": "Amount that have been received back after giving the loan over entire year",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select sum(total_payment) as total_received_amount from bankloan"
    }
   ]
  },
  {
   "title": "Average Interest Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT ROUND(AVG(int_rate) * 100, 2) FROM bankloandb.bankloan"
    }
   ]
  },
  {
   "title": "Debt to Income Ration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select round(avg(dti)*100, 5) as average_debt_to_income_ratio from bankloan\n"
    }
   ]
  },
  {
   "title": "MTD",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select count(id) as total_loan_application from bankloan where month(issue_date) = 12 and year(issue_date) = 2021"
    }
   ]
  },
  {
   "title": "MOM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select (count(id) - (select count(id) as total_loan_application from bankloan where month(issue_date) = 11 and year(issue_date) = 2021)) / (select count(id) as total_loan_application from bankloan where month(issue_date) = 11 and year(issue_date) = 2021) * 100 as mom_percentage from bankloan where month(issue_date) = 12 and year(issue_date) = 2021"
    }
   ]
  },
  {
   "title": "Total Funded Amount ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select sum(loan_amount) as total_funded_amount from bankloan where month(issue_date) = 12 and year(issue_date) = 2021"
    }
   ]
  },
  {
   "title": "MOM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select (sum(loan_amount) - (select sum(loan_amount) as total_funded_amount from bankloan where month(issue_date) = 11 and year(issue_date) = 2021)) / (select sum(loan_amount) as total_funded_amount from bankloan where month(issue_date) = 11 and year(issue_date) = 2021) * 100 as mom_percentage from bankloan where month(issue_date) = 12 and year(issue_date) = 2021\n"
    }
   ]
  },
  {
   "title": "Total Received Amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select sum(total_payment) as total_received_amount from bankloan where month(issue_date) = 12 and year(issue_date) = 2021"
    }
   ]
  },
  {
   "title": "MOM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select (sum(total_payment) - (select sum(total_payment) as total_received_amount from bankloan where month(issue_date) = 11 and year(issue_date) = 2021)) / (select sum(total_payment) as total_received_amount from bankloan where month(issue_date) = 11 and year(issue_date) = 2021) * 100 as mom_percentage from bankloan where month(issue_date) = 12 and year(issue_date) = 2021\n "
    }
   ]
  },
  {
   "title": "Total Funded Amount ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select round(avg(int_rate) * 100, 5) as average_interest_rate from bankloan where month(issue_date) = 12 and year(issue_date) = 2021"
    }
   ]
  },
  {
   "title": "MOM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select (round(avg(int_rate) * 100, 5) - (select round(avg(int_rate) * 100, 5) as average_interest_rate from bankloan where month(issue_date) = 11 and year(issue_date) = 2021)) / (select round(avg(int_rate) * 100, 5) as average_interest_rate from bankloan where month(issue_date) = 11 and year(issue_date) = 2021) * 100 as mom_percentage from bankloan where month(issue_date) = 12 and year(issue_date) = 2021\n"
    }
   ]
  },
  {
   "title": "Total Funded Amount ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select round(avg(dti)*100, 5) as average_debt_to_income_ratio from bankloan where month(issue_date) = 12 and year(issue_date) = 2021"
    }
   ]
  },
  {
   "title": "MOM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select (round(avg(dti), 5) - (select round(avg(dti), 5) as average_debt_to_income_ratio from bankloan where month(issue_date) = 11 and year(issue_date) = 2021)) / (select round(avg(dti), 5) as average_debt_to_income_ratio from bankloan where month(issue_date) = 11 and year(issue_date) = 2021) * 100 as mom_percentage from bankloan where month(issue_date) = 12 and year(issue_date) = 2021\n"
    }
   ]
  },
  {
   "title": "Monthly Average Interest rate",
   "type": "trend",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select month(issue_date) as month, round(avg(int_rate) * 100, 5) as average_interest_rate from bankloan group by month(issue_date) order by month(issue_date)\n"
    }
   ]
  },
  {
   "title": "Average Debt to Income Ratio",
   "type": "trend",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select\n   month(issue_date) as month,\n   round(avg(dti), 5) as average_debt_to_income_ratio\nfrom bankloan\ngroup by month(issue_date)\norder by month(issue_date)"
    }
   ]
  },
  {
   "title": "Total Loan Applications",
   "type": "trend",
   "description": "This Shows the Trend of the number of people applying for loans",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT \n   MONTH(issue_date) AS month,\n   MONTHNAME(issue_date) AS month_name, \n   COUNT(id) AS total_loan_applications\nFROM bankloan\nGROUP BY MONTH(issue_date), MONTHNAME(issue_date)\nORDER BY MONTH(issue_date)\n"
    }
   ]
  },
  {
   "title": "Regional Trend by state",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT \n   address_state,\n   COUNT(id) AS total_loan_applications\nFROM bankloan\nGROUP BY address_state\n"
    }
   ]
  },
  {
   "title": "Loan Applied Based on Term",
   "type": "piechart",
   "description": "Number of people categorized based on time period of the loan",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT term, COUNT(*) AS count\nFROM bankloandb.bankloan\nGROUP BY term;"
    }
   ]
  },
  {
   "title": "Working People",
   "type": "piechart",
   "description": "Number of people categorized based on how much time they were in the job market i.e the earning folks",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT emp_length, COUNT(*) AS count\nFROM bankloandb.bankloan\nGROUP BY emp_length;"
    }
   ]
  },
  {
   "title": "Good Loan Applicants",
   "type": "stat",
   "description": "Number of people who have take good loans that is their current loan status is either fully paid or else they are paying regularly",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select count(case when loan_status = \"Fully Paid\" or loan_status = \"Current\" then id end) as good_loan_application from bankloan"
    }
   ]
  },
  {
   "title": "Good and Bad Loan",
   "type": "piechart",
   "gridPos": { "h": 19, "w": 11, "x": 7, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select (count(case when loan_status = \"Fully Paid\" or loan_status = \"Current\" then id end)*100) / count(id) as good_loan_percentage from bankloan\n"
    },
    {
     "dataset": "bankloandb",
     "rawSql": "select (count(case when loan_status = \"Charged Off\" then id end)*100) / count(id) as bad_loan_percentage from bankloan"
    }
   ]
  },
  {
   "title": "Bad Loan Applicants",
   "type": "stat",
   "description": "The amount of people who's loans has been charge off which means people who failed to pay the loans regulary",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select count(case when loan_status = \"Charged Off\" then id end) as good_loan_application from bankloan"
    }
   ]
  },
  {
   "title": "Funded Amount",
   "type": "stat",
   "description": "The amount of money that has been taken from the Bank by the people under the category of good loan ",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select sum(case when loan_status = \"Fully Paid\" or loan_status = \"Current\" then loan_amount end) as good_loan_funded_amount from bankloan"
    }
   ]
  },
  {
   "title": "Funded Amount",
   "type": "stat",
   "description": "The amount of money that the bank has given to the people under the bad loan category",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select sum(case when loan_status = \"Charged Off\" then loan_amount end) as good_loan_funded_amount from bankloan"
    }
   ]
  },
  {
   "title": "Received Amount",
   "type": "stat",
   "description": "The amount of money that has been paid back with the interest to the Bank from the people under the good loan category",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select sum(case when loan_status = \"Fully Paid\" or loan_status = \"Current\" then total_payment end) as good_loan_funded_amount from bankloan"
    }
   ]
  },
  {
   "title": "Received Amount",
   "type": "stat",
   "description": "The amount of money that has been finally retrieved from the people under the bad loan category",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select sum(case when loan_status = \"Charged Off\" then total_payment end) as good_loan_funded_amount from bankloan"
    }
   ]
  },
  {
   "title": "Segregation of good loans and bad loans state wise",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "select \n  address_state,\n  count(case when loan_status = \"Fully Paid\" then id end) as good_loan_count,\n  count(case when loan_status = \"Charged Off\" then id end) as bad_loan_count,\n  count(id) as total_loans,\n  (count(case when loan_status = \"Charged Off\" then id end) / count(id) * 100) as bad_loan_percentage\nfrom bankloan\ngroup by address_state\n"
    }
   ]
  },
  {
   "title": "Class Division of people",
   "type": "piechart",
   "description": "Poor is less than 25K dollars\nMiddle calss if between 25K to 75K\nRich Class if greater than 75K \n\nThese are annual income",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT\n   CASE\n       WHEN annual_income <= 25000 THEN 'Poor'\n       WHEN annual_income BETWEEN 25001 AND 75000 THEN 'Middle Class'\n       WHEN annual_income > 75000 THEN 'High Class'\n   END AS annual_income_group,\n   COUNT(id) AS total_loan_applications\nFROM bankloan\nGROUP BY annual_income_group\n"
    }
   ]
  },
  {
   "title": "Average Loan Amount Based on Classes",
   "type": "barchart",
   "description": "This field tells us about the average loan amount based on classes and how they are divided ... one thing we can infer is the middle class and the high class tend to take more loan ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT\n  CASE\n      WHEN annual_income <= 25000 THEN 'Poor'\n      WHEN annual_income BETWEEN 25001 AND 75000 THEN 'Middle Class'\n      WHEN annual_income > 75000 THEN 'High Class'\n  END AS annual_income_group,    \n  AVG(loan_amount) AS avg_loan_amount\nFROM bankloan\nGROUP BY annual_income_group"
    }
   ]
  },
  {
   "title": "Repayment Ratio based on class",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "WITH categorizedDF AS (\n    SELECT\n        CASE\n            WHEN annual_income <= 25000 THEN 'Low Income'\n            WHEN annual_income BETWEEN 25001 AND 75000 THEN 'Middle Income'\n            ELSE 'High Income'\n        END AS income_class,\n        loan_status\n    FROM bankloan\n)\nSELECT\n    income_class,\n    SUM(CASE WHEN loan_status = 'Fully Paid' THEN 1 ELSE 0 END) AS fully_paid_count,\n    COUNT(*) AS total_count,\n    (SUM(CASE WHEN loan_status = 'Fully Paid' THEN 1 ELSE 0 END) / COUNT(*)) * 100 AS repayment_rate\nFROM categorizedDF\nwhere income_class = \"High Income\""
    }
   ]
  },
  {
   "title": "Repayment Ratio based on class",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "WITH categorizedDF AS (\n    SELECT\n        CASE\n            WHEN annual_income <= 25000 THEN 'Low Income'\n            WHEN annual_income BETWEEN 25001 AND 75000 THEN 'Middle Income'\n            ELSE 'High Income'\n        END AS income_class,\n        loan_status\n    FROM bankloan\n)\nSELECT\n    income_class,\n    SUM(CASE WHEN loan_status = 'Fully Paid' THEN 1 ELSE 0 END) AS fully_paid_count,\n    COUNT(*) AS total_count,\n    (SUM(CASE WHEN loan_status = 'Fully Paid' THEN 1 ELSE 0 END) / COUNT(*)) * 100 AS repayment_rate\nFROM categorizedDF\nwhere income_class = \"Middle Income\""
    }
   ]
  },
  {
   "title": "Repayment Ratio based on class",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "WITH categorizedDF AS (\n    SELECT\n        CASE\n            WHEN annual_income <= 25000 THEN 'Low Income'\n            WHEN annual_income BETWEEN 25001 AND 75000 THEN 'Middle Income'\n            ELSE 'High Income'\n        END AS income_class,\n        loan_status\n    FROM bankloan\n)\nSELECT\n    income_class,\n    SUM(CASE WHEN loan_status = 'Fully Paid' THEN 1 ELSE 0 END) AS fully_paid_count,\n    COUNT(*) AS total_count,\n    (SUM(CASE WHEN loan_status = 'Fully Paid' THEN 1 ELSE 0 END) / COUNT(*)) * 100 AS repayment_rate\nFROM categorizedDF\nwhere income_class = \"Low Income\""
    }
   ]
  },
  {
   "title": "Highest Annual Income",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT MAX(annual_income) AS highest_annual_income FROM bankloandb.bankloan\n"
    }
   ]
  },
  {
   "title": "Lowest Annual Income",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT MIN(annual_income) AS highest_annual_income FROM bankloandb.bankloan\n"
    }
   ]
  },
  {
   "title": "Requirements of High Class",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 111 },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT annual_income_group, purpose, COUNT(*) as count\nFROM (\n    SELECT *,\n       CASE\n           WHEN annual_income <= 25000 THEN 'Poor'\n           WHEN annual_income BETWEEN 25001 AND 75000 THEN 'Middle Class'\n           WHEN annual_income > 75000 THEN 'High Class'\n       END AS annual_income_group\n    FROM bankloan\n) AS income_groups\nWHERE annual_income_group = 'High Class'\nGROUP BY annual_income_group, purpose\nORDER BY count DESC;\n\n"
    }
   ]
  },
  {
   "title": "Requirements of Middle Class",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 111 },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT annual_income_group, purpose, COUNT(*) as count\nFROM (\n    SELECT *,\n       CASE\n           WHEN annual_income <= 25000 THEN 'Poor'\n           WHEN annual_income BETWEEN 25001 AND 75000 THEN 'Middle Class'\n           WHEN annual_income > 75000 THEN 'High Class'\n       END AS annual_income_group\n    FROM bankloan\n) AS income_groups\nWHERE annual_income_group = 'Middle Class'\nGROUP BY annual_income_group, purpose\nORDER BY count DESC;\n\n"
    }
   ]
  },
  {
   "title": "Requirements of Poor Class",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 111 },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT annual_income_group, purpose, COUNT(*) as count\nFROM (\n    SELECT *,\n       CASE\n           WHEN annual_income <= 25000 THEN 'Poor'\n           WHEN annual_income BETWEEN 25001 AND 75000 THEN 'Middle Class'\n           WHEN annual_income > 75000 THEN 'High Class'\n       END AS annual_income_group\n    FROM bankloan\n) AS income_groups\nWHERE annual_income_group = 'High Class'\nGROUP BY annual_income_group, purpose\nORDER BY count DESC;\n\n"
    }
   ]
  },
  {
   "title": "Analysis Based on Grades",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 121 },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT DISTINCT grade,\n      AVG(int_rate) OVER (PARTITION BY grade) * 100 AS avg_interest_rate_percentage\nFROM bankloan"
    }
   ]
  },
  {
   "title": "Purpose Of Loan",
   "type": "piechart",
   "description": "Loan applications categorized based on purpose of category by each individual.",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 121 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bankloandb",
     "rawSql": "SELECT purpose, COUNT(*) AS count\nFROM bankloandb.bankloan\nGROUP BY purpose;"
    }
   ]
  }
 ]
}